#[Info]
site_name: Web Security Study
site_url: https://web.1cepeak.cn #网站地址
site_author: 1cePeak #作者名
#[UI]
theme:
  name: material
  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换深色模式
    # Toggle dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切换浅色模式
  features: 
    - navigation.instant #- header.autohide  #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand # 打开Tab时左侧目录全部展开
    #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
  language: zh # 一些提示性的文字会变成中文


  icon: 
    repo: fontawesome/brands/github # 右上角图标
edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/1ceP3ak/WebSecurity # 右上角点击跳转的链接
repo_name: 1ceP3ak.github.io # 右上角的名字

# [Navigtion]
nav: 
  - 主页: "index.md"
  #   - 好用/好玩网站分享: blog/Webplay.md
  #   - What is Github: blog/Github.md
  #   - 解决谷歌翻译用不了的问题: blog/googletranslate.md
  #   - Mac/windows软件网站汇总: blog/macsoft.md
  #   - win11资源分享: blog/win.md
  #   - Telegram 群组、频道、机器人 - 汇总分享: blog/TG.md
  #   - Python:
  #       - 将Python文件.py打包成.exe可执行程序: blog/py/python.md
  #       - pip: blog/py/pip.md
  #   - C语言: blog/c.md
  #   - kexueshangwang: blog/kexue.md
  # - 开发: 
  #   - Markdown: develop/markdown.md
  #   - MWeb Pro: develop/MWeb.md
  #   - 大厂们的良心软件～: develop/fenxiang.md
  #   - 写给所有 Mac 用户的摸鱼指北: develop/Mac.md
  # - 闲话:
  #   - 原神: relax/game.md
  #   - 诗文:
  #     - 滕王阁序: relax/shiwen/twgx.md
  #     - 望江南·超然台作: relax/shiwen/sjcnh.md
  #     - 击鼓: relax/shiwen/jg.md
  #     - 雨霖铃·秋别: relax/shiwen/yll.md
  # - 旅行: 
  #   - 家乡: trip/LH.md
  #   - 重庆: trip/travel.md
  # - 关于:
  #   - 个人履历: about/geren.md
  #   - 网站制作: about/web.md




copyright: Copyright &copy; 1cePeak # 左下角的版权声明


extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  # social:
  #   - icon: fontawesome/brands/twitter 
  #     link: https://twitter.com/wcowin_
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/Wcowin
  #   - icon: fontawesome/brands/bilibili
  #     link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
  #   - icon: fontawesome/solid/paper-plane
  #     link: mailto:<1135801806@qq.com> #联系方式